In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Initial Data Inspection

In [2]:
df = pd.read_csv("../data/raw/insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [4]:
df.shape

(1338, 7)

In [5]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [6]:
df = df.drop_duplicates()

In [7]:
df.duplicated().sum()

np.int64(0)

## Encoding categorical values

In [8]:
df.sex.value_counts()

sex
male      675
female    662
Name: count, dtype: int64

In [9]:
df.sex = df.sex.map({"male":1, "female":0})

In [10]:
df.sample(3)

     age  sex   bmi  children smoker     region    charges
500   29    1  34.4         0    yes  southwest  36197.699
94    64    0  31.3         2    yes  southwest  47291.055
268   45    1  30.2         1     no  southwest   7441.053

In [11]:
df.sex.value_counts(), df.sex.dtype

(sex
 1    675
 0    662
 Name: count, dtype: int64,
 dtype('int64'))

In [12]:
df.smoker.value_counts()

smoker
no     1063
yes     274
Name: count, dtype: int64

In [13]:
df.smoker = df.smoker.map({"yes": 1, "no": 0})

In [14]:
df.smoker

0       1
1       0
2       0
3       0
4       0
       ..
1333    0
1334    0
1335    0
1336    0
1337    1
Name: smoker, Length: 1337, dtype: int64

In [15]:
df.region.value_counts()

region
southeast    364
southwest    325
northwest    324
northeast    324
Name: count, dtype: int64

In [16]:
df = pd.get_dummies(df, columns=["region"], drop_first=True, dtype=int)

In [17]:
df.head()

,age,sex,bmi,children,smoker,charges,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,16884.92400,0,0,1
1,18,1,33.770,1,0,1725.55230,0,1,0
2,28,1,33.000,3,0,4449.46200,0,1,0
3,33,1,22.705,0,0,21984.47061,1,0,0
4,32,1,28.880,0,0,3866.85520,1,0,0

# Saving processed data

In [20]:
df.to_csv("processed_insurance.csv", index=False)